language: node_js
node_js: "0.8"
before_install:
 - echo "*** Installing bower..."
 - npm install -g bower
 - echo "*** Installing grunt..."
 - npm install -g grunt
install:
 - echo "*** Installing node modules..."
 - npm install
 - echo "*** Clearing bower cache..."
 - bower cache-clean
 - echo "*** Installing application libraries..."
 - bower install
 - echo "*** All done!"
before_script:
 - ls -lR
 - sudo apt-get update -qq
 - sudo apt-get install -qq ruby nasm
 - gem install compass
script: grunt build