language: node_js
node_js: "0.8"
install:
 - echo "*** Installing node modules..."
 - npm install
 - echo "*** Clearing bower cache..."
 - bower cache-clean
 - echo "*** Installing application libraries..."
 - bower install
before_script:
 - ls -lR app
 - sudo apt-get update -qq
 - sudo apt-get install -qq ruby nasm
 - gem install compass
script: grunt build