language: node_js
node_js: "0.8"
install:
 - npm install
 - bower cache-clean
 - bower install
before_script:
 - ls -lR
 - sudo apt-get update -qq
 - sudo apt-get install -qq ruby nasm
 - gem install compass
script: grunt build